### ISSUE TITLE
Incorrect example on the screenshot

### ISSUE THREAD

**Issue by pnedelko** [elasticio/code-component#11]
<img width="463" alt="code-component: The holy grail of the elastic io platform 2019-03-21 16-10-12" src="https://user-images.githubusercontent.com/2523461/54762436-6cbdeb00-4bf4-11e9-8941-3110c7f069fc.png">

I've tried to implement the construction provided on the screenshot and failed, because if you specify the `msg` as an argument, you always get `msg=undefined`. The solution is to leave the arguments list empty and get `msg` from the "outside".

**Comment by zubairov** [comment]
yes, agree, the screenshot is completely misleading and wrong. `msg` is an implicit variable:

![image](https://user-images.githubusercontent.com/56208/54816914-dc37e700-4c95-11e9-99ac-5e4a306f7056.png)

making it explicit breaks the whole code component

**Comment by jhorbulyk** [comment]
We no longer have that screenshot so I think this issue can be closed.
