### ISSUE TITLE
Add support for snapshots

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/code-component#20]
Node.js component should support snapshots feature.

## Acceptance criterias
- [ ] `run` function accepts 3 arguments: `msg`, `cfg`, `snapshot`
- [ ] `cfg` param is always an object with 1 property: `code` (the code in text format)
- [ ] `snapshot` is an empty object (`{}`) by default
- [ ] it should be possible to modify the snapshot by doing `this.emit('snapshot', snapshot)`. The behaviour should be the same as for the normal component.

**Comment by stas-fomenko** [comment]
@jhorbulyk @pnedelko 
could this task be closed according to this pr https://github.com/elasticio/code-component/pull/27?

**Comment by jhorbulyk** [comment]
> could this task be closed according to this pr #27?
Sure
