### ISSUE TITLE
If we export "co-request" to the process, we should also export "co"

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/code-component#8]
If you [look at the list of libraries exported to the code process](https://github.com/elasticio/code-component/blob/master/actions/code.js), we export ``co-request`` as the only library capable of making outgoing web requests.  If you look at the [samples for that module](https://www.npmjs.com/package/co-request), they all make use of ``co`` which is not available to the user unless they require it.

**Comment by zubairov** [comment]
Do you think it would be better just to drop `co` support completely and use `async/await` instead?

**Comment by jhorbulyk** [comment]
That is probably even better.  I'm not sure how to do so in a backwards compatable way since we export ``co-request`` as ``request`` and presumably lots of our users call the provided ``request`` method.

**Comment by jhorbulyk** [comment]
We adapted async/await and so this issue can be closed.
